import SkeletonLazyImage from "@/components/basic/skeleton-lazy-image";
import Head from "next/head"
import Image from "next/image"

import HeaderSearch from "@/components/complex/header-search";
import HeaderLoginRegisterButton from "@/components/basic/header-login-register-button";
import { HeaderBasket } from "@/components/basic/header-basket";
import { MegaMeno } from "@/components/basic/mega-menu";
import { GalleriaIndicatorDemo } from "@/components/complex/gallery";
import { SelectCityModal } from "@/components/complex/select-city-modal";
import { InfoBadges } from "@/components/complex/info-badges";
import OrderPanel from "@/components/complex/order-panel";
import MostViewed from "@/components/complex/most-viewed";
import MostSelled from "@/components/complex/most-selled";
import { FooterLinks } from "@/components/complex/footer";
import LoginRegisterModal from "@/components/complex/auth-utils/login-register-modal";
import React, { Component } from "react";
import Header from "@/components/complex/header";


export default class Home extends React.Component {

componentDidMount(): void {
  if ("serviceWorker" in navigator) {
      navigator.serviceWorker.register("/sw.js").then(
        function (registration) {
          console.log(
            "Service Worker registration successful with scope: ",
            registration.scope
          );
        },
        function (err) {
          console.log("Service Worker registration failed: ", err);
        }
      );
  }
}

  render() {
    let links: { link: string; label: string }[] = [{ link: "", label: "" }];
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          {/* <link rel="icon" href={logo} /> */}
        </Head>
        <main >
          <div >


            <Header/>




            <GalleriaIndicatorDemo />
            <br />
            <InfoBadges />
            <br />

            <div className="container">

              <div className="d-flex justify-content-evenly ">

                <OrderPanel />
              </div>
            </div>
            <br />

            <div className='container'>
              {/*<MostViewed />*/}
            </div>
            <br />
            <div className='container'>
              {/*<MostSelled />*/}
            </div>



          </div>
          <br />

          <FooterLinks />
        </main>
      </>
    )
  }
}